services:
  # Backend web service
  - type: web
    name: aquagreen-monitoring-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python manage.py migrate && gunicorn data_processor.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: aquagreen-db
          property: connectionString
      - key: DJANGO_ALLOWED_HOSTS
        value: "aquagreen-monitoring-backend.onrender.com,yourfrontenddomain.vercel.app"

  # Database
  - type: pgsql
    name: aquagreen-db
    ipAllowList: [] # Allow all IPs
    plan: free

buildCommand: pip install -r backend/requirements.txt
