# Generated by Django 4.2.10 on 2025-06-04 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("file_uploader", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cropimage",
            name="csv_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="file_uploader.csvfile",
            ),
        ),
    ]
