# Generated by Django 5.0.6 on 2025-06-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_uploader', '0003_geneticdata_geneticrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='geneticdata',
            name='encrypted_metadata',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geneticdata',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='geneticrecord',
            name='encrypted_breeding_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geneticrecord',
            name='encrypted_genetic_signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
