# Generated by Django 4.2.10 on 2025-03-19 08:51

from django.db import migrations, models
import django.db.models.deletion
import file_uploader.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=file_uploader.models.get_file_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('excel_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_data', to='file_uploader.excelfile')),
            ],
        ),
    ]
