# Generated by Django 4.2.10 on 2025-06-04 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("file_uploader", "0003_auto_20250508_1525"),
    ]

    operations = [
        migrations.AlterField(
            model_name="excelfile",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="excel_files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
